### ISSUE TITLE
Module type configuration error

### ISSUE THREAD

**Issue by Kabe0** [jleeson/rollup-plugin-import-css#5]
When using in a module, the project fails to load.

```
[!] SyntaxError: Cannot use import statement outside a module
/node_modules/rollup-plugin-import-css/dist/plugin.esm.js:1
import{createFilter as _}from"@rollup/pluginutils";import y from"path";var $=(e={})=>{var n,c,p;e.transform||(e.transform=r=>r);const f={},O=(n=e.alwaysOutput)!=null?n:!1,x=_((c=e.include)!=null?c:["**/*.css"],(p=e.exclude)!=null?p:[]),d=(r,l,a=new Set)=>{if(a.has(r))return[];a.add(r);const t=[r];return l(r).importedIds.forEach(u=>{t.push(...d(u,l,a))}),t};return{name:"import-css",transform(r,l){if(!x(l))return;const a=e.minify?b(e.transform(r)):e.transform(r);return(!f[l]||f[l]!=a)&&(f[l]=a),{code:`export default ${JSON.stringify(a)};`,map:{mappings:""}}},generateBundle(r,l){var a,t;let u={},m=null;for(let s in l)u=Object.assign(u,l[s].modules),m||(m=l[s].facadeModuleId);const g=d(m,this.getModuleInfo),o=Object.entries(f).sort((s,i)=>g.indexOf(s[0])-g.indexOf(i[0])).map(([s,i])=>{if(!u[s])return i}).join(`
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at Loader.import (internal/modules/esm/loader.js:178:24)
    at loadConfigFile (node_modules/rollup/dist/shared/loadConfigFile.js:568:16)
    at Object.loadAndParseConfigFile (node_modules/rollup/dist/shared/loadConfigFile.js:545:21)

error Command failed with exit code 1.
```

This happens when the main root project configuration is set to "type": "module".

**Comment by Kabe0** [comment]
Take a look at the following file config.. This fixes the problem

```
{
  "name": "rollup-plugin-import-css",
  "version": "3.0.2",
  "description": "A Rollup plugin to import CSS into JavaScript",
  "main": "dist/plugin.cjs.js",
  "module": "dist/plugin.esm.mjs",
  "types": "types/plugin.d.ts",
  "scripts": {
    "build": "rollup -c",
    "lint": "eslint src",
    "prepublishOnly": "npm run lint && npm run build"
  },
  "keywords": [
    "rollup",
    "rollup-plugin",
    "css",
    "import"
  ],
  "files": [
    "dist",
    "types"
  ],
  "exports": {
    ".": {
      "require": "./dist/plugin.cjs.js",
      "import": "./dist/plugin.esm.mjs",
      "default": "./dist/plugin.esm.js"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jleeson/rollup-plugin-import-css.git"
  },
  "bugs": {
    "url": "https://github.com/jleeson/rollup-plugin-import-css/issues"
  },
  "homepage": "https://github.com/jleeson/rollup-plugin-import-css#readme",
  "author": "Jacob Leeson <jleeson2000@gmail.com> (https://twitter.com/jleesons)",
  "license": "MIT",
  "devDependencies": {
    "esbuild": "^0.12.28",
    "eslint": "^7.32.0",
    "rollup": "^2.56.3",
    "rollup-plugin-esbuild": "^4.5.0"
  },
  "dependencies": {
    "@rollup/pluginutils": "^4.1.1"
  },
  "peerDependencies": {
    "rollup": "^2.x.x"
  }
}
```

It appears it's sensitive to the .mjs extension.

**Comment by jleeson** [comment]
Thanks for opening this issue, you are right the current package.json is setup for use in bundlers and not native modules.
As your PR (#6) suggests changing the esm output to use the .mjs extensions should resolve this.

**Comment by jleeson** [comment]
Pushed the fix in the latest update. (rollup-plugin-import-css@3.0.3)
